[workspace]
resolver = "2"
members = ["examples/*"]


[workspace.dependencies]
# basic dependencies
napi-ohos = { path = "../project/ohos-rs/ohos-rs/crates/napi" }
napi-derive-ohos = { path = "../project/ohos-rs/ohos-rs/crates/macro" }
winit = { path = "../project/southorange/winit" }
wry = { path = "../project/southorange/wry" }
openharmony-ability = { path = "../project/ohos-rs/openharmony-activity/crates/ability" }
openharmony-ability-derive = { path = "../project/ohos-rs/openharmony-activity/crates/derive" }



# build dependencies
napi-build-ohos = { path = "../project/ohos-rs/ohos-rs/crates/build" }

# external dependencies
dpi = "0.1"
